name: GitHub Actions eslint
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm make lint